name = "mon-portfolio"  # Remplace par le vrai nom du projet Cloudflare Pages

kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

[build]
command = "npm run build"

pages_build_output_dir = "./build"

